server:
  port: 8081  # Aligné avec application.properties

spring:
  application:
    name: HIRFA

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Corrigé de MySQL8Dialect à PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  flyway:
    enabled: false  # Désactivé Flyway pour éviter l'erreur PostgreSQL 17.6
    ignore-migration-patterns: "*:missing,*:future"  # Corrigé la syntaxe (enlevé le : final)

  # Datasource IA (Postgres/Supabase)
  ai-datasource:
    url: jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:6543/postgres
    username: postgres.stpbxylzfdtlqffkcpuo
    password: Hirfa2025@
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  # Scheduler
  task:
    scheduling:
      pool:
        size: 2
