server:
  port: 8080

spring:
  application:
    name: HIRFA

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  # Datasource IA (Postgres/Supabase)
  ai-datasource:
    url: jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:6543/postgres
    username: postgres.stpbxylzfdtlqffkcpuo
    password: Hirfa2025@
    driver-class-name: org.postgresql.Driver
    # Optionnel: pool Hikari
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

# Scheduler on
spring.task.scheduling.pool.size: 2
